[package]
name = "tiny_http_fork"
version = "0.12.8"
authors = ["pierre.krieger1708@gmail.com","Corey Farwell <coreyf@rwell.org>", "Aleksandr Morozov <alex@4neko.org>"]
description = "Low level HTTP server library FORK"
documentation = "https://tiny-http.github.io/tiny-http/tiny_http_fork/index.html"
keywords = ["http", "server", "web"]
license = "MIT OR Apache-2.0"
repository = "https://codeberg.org/4neko/tiny-http-fork"
edition = "2024"
rust-version = "1.85"

[features]
default = ["log"]

ssl = ["ssl-rustls"]
ssl-openssl = ["dep:openssl", "dep:zeroize"]
ssl-rustls = ["dep:rustls", "dep:rustls-pemfile", "dep:zeroize"]
ssl-native-tls = ["dep:native-tls", "dep:zeroize"]

[dependencies]
ascii = "1.1"
chunked_transfer = "1"
httpdate = "1.0"

log = { version = "0.4", optional = true }
openssl = { version = "0.10", optional = true }
rustls = { version = "0.23", optional = true }
rustls-pemfile = { version = "2.2", optional = true }
zeroize = { version = "1", optional = true }
native-tls = { version = "0.2", optional = true }

[dev-dependencies]
rustc-serialize = "0.3"
sha1 = "0.11.0"
fdlimit = "0.3"
tempfile = "~3.27"

[package.metadata.docs.rs]
# Enable just one SSL implementation
features = ["ssl-rustls"]

[[example]]
name = "hello-world"
required-features = ["log"]

[[example]]
name = "php-cgi"
required-features = ["log"]

[[example]]
name = "readme-example"
required-features = ["log"]

[[example]]
name = "serve-root"
required-features = ["log"]

[[example]]
name = "ssl"
required-features = ["log", "ssl-rustls"]

[[example]]
name = "websockets"
required-features = ["log"]
