name: linux-os-test-arm64
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs: 
  linux-test:
    runs-on: ubuntu-act24-arm
    container:
      image: registry:5000/ubuntu:rust-runner-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Rust version
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          rustc --version
      
      - name: Cargo Cache
        # Optional: Speeds up builds significantly in Forgejo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run build debug (features std)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo build --all-targets --no-default-features 

      - name: Run checks (features std)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo check --all-targets --no-default-features 

      - name: Run tests (features std)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo test --no-default-features 
#-- 
      - name: Run build debug (features std,use_ring)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo build --all-targets --no-default-features --features ssl-rustls

      - name: Run checks (features std,use_ring)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo check --all-targets --no-default-features --features ssl-rustls

      - name: Run tests (features std,use_ring)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo test --no-default-features --features ssl-rustls
# -- 
      - name: Run build debug (features std,use_aws_lc)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo build --all-targets --no-default-features --features ssl-native-tls

      - name: Run checks (features use_aws_lc)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo check --all-targets --no-default-features --features ssl-native-tls

      - name: Run tests (features std,use_aws_lc)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo test --no-default-features --features ssl-native-tls
# -- use_openssl
      - name: Run build debug (features std,use_openssl)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo build --all-targets --no-default-features --features ssl-openssl

      - name: Run checks (features std,use_openssl)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo check --all-targets --no-default-features --features ssl-openssl

      - name: Run tests (features std,use_openssl)
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          cargo test --no-default-features --features ssl-openssl



