name: linux-os-test
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs: 
  linux-test:
    runs-on: ubuntu-latest
    container:
      image: registry:5000/ubuntu:rust-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Rust version
        run: rustc --version
      
      - name: Cargo Cache
        # Optional: Speeds up builds significantly in Forgejo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run build debug (features task_pool_legacy)
        run: cargo build --all-targets --no-default-features --features task_pool_legacy

      - name: Run checks (features )
        run: cargo check --all-targets --no-default-features --features task_pool_legacy

      - name: Run tests (features )
        run: cargo test --no-default-features --features task_pool_legacy
# --  
      - name: Run build debug (features task_pool_channel)
        run: cargo build --all-targets --no-default-features --features task_pool_channel

      - name: Run checks (features )
        run: cargo check --all-targets --no-default-features --features task_pool_channel

      - name: Run tests (features )
        run: cargo test --no-default-features --features task_pool_channel
# -- ssl-rustls
      - name: Run build debug (features ssl-rustls)
        run: cargo build --all-targets --no-default-features --features ssl-rustls,task_pool_legacy

      - name: Run checks (features )
        run: cargo check --all-targets --no-default-features --features ssl-rustls,task_pool_legacy

      - name: Run tests (features )
        run: cargo test --no-default-features --features ssl-rustls,task_pool_legacy
# -- ssl-native-tls
      - name: Run build debug (features ssl-native-tls)
        run: cargo build --all-targets --no-default-features --features ssl-native-tls,task_pool_legacy

      - name: Run checks (features )
        run: cargo check --all-targets --no-default-features --features ssl-native-tls,task_pool_legacy

      - name: Run tests (features )
        run: cargo test --no-default-features --features ssl-native-tls,task_pool_legacy
# -- ssl-openssl
      - name: Run build debug (features ssl-openssl)
        run: cargo build --all-targets --no-default-features --features ssl-openssl,task_pool_legacy

      - name: Run checks (features )
        run: cargo check --all-targets --no-default-features --features ssl-openssl,task_pool_legacy

      - name: Run tests (features )
        run: cargo test --no-default-features --features ssl-openssl,task_pool_legacy