name: netbsd-os-test
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs: 
  netbsd-test:
    runs-on: ubuntu-latest
    container:
      image: registry:5000/ubuntu-vm:runner-24.04
      volumes:
        - /vm_images:/vm_images
      options: >-
        --device /dev/kvm
        --device /dev/loop-control
        --device /dev/loop0
        --device /dev/loop1
        --device /dev/loop2
        --device /dev/loop3
        --device /dev/loop4
        --device /dev/loop5
        --device /dev/loop6
#        --privileged

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Loop check
        run: |
          ls /dev | grep loop

      - name: Start server background process
        run: |
          python3 -m http.server 8080 --directory /vm_images &
          sleep 2 # Give it a second to start

      - name: Test server
        run: |
          ls -la /vm_images
          curl --head http://localhost:8080/netbsd-10.1-x86-64.qcow2


      - name: Run in NetBSD
        uses: https://github.com/cross-platform-actions/action@v1.3.0
        with:
          operating_system: netbsd
          version: '10.1'
          image_url: http://localhost:8080/netbsd-10.1-x86-64.qcow2
          memory: 4G
          cpu_count: 3
          shell: bash 
          run: |
            uname -a
            export OPENSSL_DIR=/usr/pkg
            export OPENSSL_LIB_DIR=/usr/pkg/lib
            export OPENSSL_INCLUDE_DIR=/usr/pkg/include
            export LD_LIBRARY_PATH=/usr/pkg/lib:$LD_LIBRARY_PATH
            export PATH="$HOME/.cargo/bin:$PATH"
            rustc --version
            cargo build --all-targets --no-default-features 
            cargo check --all-targets --no-default-features 
            cargo test --verbose --no-default-features 
            cargo build --all-targets --no-default-features --features ssl-rustls
            cargo check --all-targets --no-default-features --features ssl-rustls
            cargo test --verbose --no-default-features --features ssl-rustls
            cargo build --all-targets --no-default-features --features ssl-native-tls
            cargo check --all-targets --no-default-features --features ssl-native-tls
            cargo test --verbose --no-default-features --features ssl-native-tls
            cargo build --all-targets --no-default-features --features ssl-openssl
            cargo check --all-targets --no-default-features --features ssl-openssl
            cargo test --verbose --no-default-features --features ssl-openssl
